// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjIbA7wC4si3wXwNBVxGe5Pv1e9oNm5rc',
    appId: '1:1002776845743:web:9435c5ecbfdbcd92e6635a',
    messagingSenderId: '1002776845743',
    projectId: 'sportlingo-a93f2',
    authDomain: 'sportlingo-a93f2.firebaseapp.com',
    databaseURL: 'https://sportlingo-a93f2-default-rtdb.firebaseio.com',
    storageBucket: 'sportlingo-a93f2.appspot.com',
    measurementId: 'G-K4C2SXMZ2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rfSgC-0VRgmZK41C7XjFctgVisArjOU',
    appId: '1:1002776845743:android:f56f1a358b76a72be6635a',
    messagingSenderId: '1002776845743',
    projectId: 'sportlingo-a93f2',
    databaseURL: 'https://sportlingo-a93f2-default-rtdb.firebaseio.com',
    storageBucket: 'sportlingo-a93f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIrAayZGHL3z5-S3XbYcoUGYtUMtqqf0',
    appId: '1:1002776845743:ios:9248bf29fe895019e6635a',
    messagingSenderId: '1002776845743',
    projectId: 'sportlingo-a93f2',
    databaseURL: 'https://sportlingo-a93f2-default-rtdb.firebaseio.com',
    storageBucket: 'sportlingo-a93f2.appspot.com',
    androidClientId: '1002776845743-g58ukattjsn20qgjjijkque27t1ont6k.apps.googleusercontent.com',
    iosClientId: '1002776845743-sihep0mep3q22q5gkqg9qg0v4nkeq6j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportlingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIrAayZGHL3z5-S3XbYcoUGYtUMtqqf0',
    appId: '1:1002776845743:ios:4b3a7d0593039c47e6635a',
    messagingSenderId: '1002776845743',
    projectId: 'sportlingo-a93f2',
    databaseURL: 'https://sportlingo-a93f2-default-rtdb.firebaseio.com',
    storageBucket: 'sportlingo-a93f2.appspot.com',
    androidClientId: '1002776845743-g58ukattjsn20qgjjijkque27t1ont6k.apps.googleusercontent.com',
    iosClientId: '1002776845743-qhm2qql6g7j8la47lcicb47pkrqrm9lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportlingo.RunnerTests',
  );
}
